image: centos:centos6.6

variables:
    BUILD_DIR: ./_build

stages:
    - build
    - test
    - rpm
    - pkg
    - release

build:
    stage: build
    tags:
        - dev
    only:
        - develop
        - release
        - tags
    before_script:
        - yum install -y tar automake libtool
        - curl -O http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz # download newer autoconf
        - tar -xzf autoconf-2.69.tar.gz && cd autoconf-2.69
        - ./configure && make && make install
        - cd -
    script:
        - autoreconf -fvi && ./configure
        - make && make install
        - mkdir -p $BUILD_DIR/bin && mkdir -p $BUILD_DIR/conf
        - echo `pwd` 
        - cp src/nutcracker $BUILD_DIR/bin
        - cp conf/* $BUILD_DIR/conf
    artifacts:
        name: "twemproxy-${CI_PIPELINE_ID}-build"
        paths:
            - _build/
        expire_in: "3 days"
    dependencies: []

test:
    stage: test
    image: docker-compose-centos7
    tags:
        - dev
    before_script:
        - yum install -y epel-release git tar python
        - yum install -y python-pip
        - pip install nose
        - pip install git+https://github.com/andymccurdy/redis-py.git@2.10.3
        - pip install git+https://github.com/idning/python-memcached.git#egg=memcache
        - cp tests/conf/conf-ci.py tests/conf/conf.py
    script:
        - cwd=`pwd`; echo $cwd
        - cd $cwd/scripts/docker/ && sh setup.sh
        - container_name="$HOSTNAME-build"; echo $container_name
        - docker network connect twemproxy_default $container_name
        - cd $cwd/tests && nosetests -v
        - docker network disconnect twemproxy_default $container_name
        - cd $cwd/scripts/docker/ && sh teardown.sh
    dependencies: []

rpm:
    stage: pkg
    image: packager
    only:
        - release
        - tags
    except:
        - /.*-pre$/
    tags:
        - dev
    script:
        - bash package.sh
    artifacts:
        name: "twemproxy-${CI_PIPELINE_ID}-rpm"
        paths:
            - "*.rpm"
        expire_in: "1 week"
    dependencies:
        - build

release:
    stage: release
    image: rsync
    only:
        - tags
    except:
        - /.*-pre$/
    tags:
        - dev
    script:
        - mkdir _sync && cp -v *.rpm _sync
        - cd _sync && rsync -avz . 172.16.28.10::rpmRepo/
    when: manual
    dependencies:
        - rpm
